defmodule HelloBoard.Top do
  @moduledoc """
  HelloBoard — USB2 to ESP32 serial bridge on ULX3S 85F.

  Single clock domain: clk_48 (48 MHz exact via PLL).
  PHY, SIE, CDCSerial, UART, ESP32 ProgCtrl, DiagDisplay all run on clk_48.
  No CDC crossings — matches every reference USB FS implementation.

  ## Reset architecture

  pll_locked → Hw.ResetSync (reset_style: :none, 1024-cycle hold) → rst

  ResetSync runs ungated by design — it IS the reset generator. Its clock
  domain declares reset_style: :none so the elaborator emits a bare
  always @(posedge clk_48) block for it, immune to the rst signal it produces.

  ## USB pad architecture

  E16/F16 — usb_fpga_dp/dn — LVCMOS33D differential input.
  D15/E15 — usb_fpga_bd_dp/dn — bidirectional BB tristates.
  B12/C12 — usb_fpga_pu_dp/dn — D+ pullup / D- pulldown control.
  """

  use Hw.Component

  clock :clk_25mhz, freq: 25.0
  clock :clk_48,    freq: 48.0, domain: :usb, reset: :rst, reset_style: :sync

  inout  :usb_fpga_bd_dp, 1
  inout  :usb_fpga_bd_dn, 1
  output :usb_fpga_pu_dp, 1
  output :usb_fpga_pu_dn, 1

  # ESP32 UART bridge
  output :wifi_rxd,   1
  input  :wifi_txd,   1
  output :wifi_en,    1
  output :wifi_gpio0, 1

  # US1 FTDI serial (FPGA -> host). Independent diagnostic channel: the board
  # streams its sticky diagnostic latches out this pin as ASCII so the host can
  # read internal state over /dev/cu.usbserial-* without a logic analyzer.
  # (The DSLogic U2Basic is not sigrok-supported, so analyzer capture can't be
  # automated; this closes the debug loop over serial instead.)
  output :ftdi_rxd,  1

  # US1 FTDI host->FPGA line (site M1). In-band command channel: the host sends
  # a command byte down US1 and the FPGA acts on it. Currently decodes 'R' (0x52)
  # = force USB re-enumeration (drop D+ pullup + reset). Same physical US1 port
  # the diagnostic dashboard streams OUT of on ftdi_rxd.
  input  :ftdi_txd,  1

  output :led,  8
  output :gn12, 1

  input  :btn1, 1
  input  :btn2, 1

  # Logic analyzer probe outputs — J1 header
  # RAW-BUS K-DETECT ORACLE: rx_active never rises on HW though gp0/gn0 (raw bus)
  # toggle. A K symbol (the PHY's idle->detect trigger) needs D+ low AND D- high.
  # Computed at top level from the raw bus — does NOT touch the PHY, so it cannot
  # affect enumeration. The two sticky pins (gp2/gn2) are the answer at a glance.
  # gp0 = dp_diff       (host D+ raw bus, straight off pad — trigger)
  # gn0 = dn_raw        (host D- raw bus, straight off pad)
  # gp1 = raw_dn_high   (live: raw D- high)
  # gn1 = raw_k         (live: raw K symbol = D+ low & D- high)
  # gp2 = lat_dn_high   (sticky: raw D- was EVER high)   <-- KEY: is D- even wired?
  # gn2 = lat_raw_k     (sticky: a raw K was EVER seen)   <-- KEY: does a K ever form?
  # gp3 = phy_rx_active (live: PHY declared a packet — should follow a K)
  # gn3 = usb_rx_state[0] (live: PHY RX state LSB, context)
  # GND = J1 pin 1 or 2.
  output :gp0, 1
  output :gn0, 1
  output :gp1, 1
  output :gn1, 1
  output :gp2, 1
  output :gn2, 1
  output :gp3, 1
  output :gn3, 1

  # Internal clocks and reset
  wire :clk_48,     1
  wire :pll_locked, 1
  wire :rst,        1

  # --- Re-enumeration control ---
  # reenum_pu_drop: high during a re-enum window -> force D+ pullup LOW so the
  #   host sees an unplug. rst is generated by Hw.ReEnum directly (no separate
  #   ResetSync / rst_arm indirection anymore).
  wire :reenum_pu_drop, 1
  wire :reenum_count,   4   # reset-SURVIVABLE count of re-enum windows started (from Hw.ReEnum)
  wire :phy_pu,         1   # the PHY's pullup output, before the re-enum gate
  wire :btn1_level,     1   # btn1 as a plain level trigger (active-high, PULLMODE=DOWN)
  # US1 host->FPGA UART (9600 8N1) — the in-band command channel.
  wire :us1_rx_data,  8
  wire :us1_rx_valid, 1
  wire :us1_rx_ready, 1
  wire :us1_cmd_reset, 1   # 1-cycle pulse: a 'R' (0x52) command byte arrived
  wire :us1_valid_d,   1, init: 0   # registered previous us1_rx_valid (edge detect)
  wire :us1_rx_is_r,   1            # comb: current byte is 'R' AND valid

  # USB pad wiring
  wire :dp_diff,      1
  wire :phy_dp_tx,    1
  wire :phy_dn_tx,    1
  wire :phy_tx_en,    1
  wire :dn_raw,       1
  wire :dp_raw,       1
  wire :dp_diff_n,    1

  # PHY ↔ SIE signals — all clk_48, no CDC
  wire :phy_rx_valid,  1
  wire :phy_rx_data,   1
  wire :phy_rx_se0,    1
  wire :phy_rx_active, 1
  wire :phy_rx_bit0,   1   # PID bit-0 alignment strobe (PHY -> SIE)
  wire :phy_rx_pid_done, 1 # PID last-bit strobe (PHY -> SIE)
  wire :phy_tx_valid,  1
  wire :phy_tx_data,   1
  wire :phy_tx_se0,    1
  wire :phy_tx_ready,  1

  # SIE endpoint out → CDCSerial
  wire :sie_ep_out_data,    8
  wire :sie_ep_out_valid,   1
  wire :sie_ep_out_ep,      4
  wire :sie_ep_out_setup,   1
  wire :sie_ep_out_pkt_end, 1

  # CDCSerial → SIE endpoint in
  wire :sie_ep_in_ep,       4
  wire :sie_ep_in_pid,      8
  wire :sie_ep_in_data,     8
  wire :sie_ep_in_valid,    1
  wire :sie_ep_in_loaded,   1
  wire :sie_ep_in_ready,    1
  wire :sie_ep_in_done,     1
  wire :sie_ep_in_nak,      1

  # USB device address — set by CDCSerial on SET_ADDRESS, used by SIE
  # persist: :power_on_only — must survive USB bus resets, only clear at power-on
  wire :dev_addr,   7, init: 0

  # PLL second output — unused in single-domain design
  wire :_clk_unused,    1
  wire :_phy_tx_active, 1

  # UART bridge signals
  wire :cdc_rx_data,  8
  wire :cdc_rx_valid, 1
  wire :cdc_rx_ready, 1
  wire :cdc_tx_data,  8
  wire :cdc_tx_valid, 1
  wire :cdc_tx_ready, 1
  wire :dtr,          1
  wire :rts,          1

  # CDC state for diagnostics
  wire :cdc_dev_state,  2
  wire :cdc_ep0_state,  2
  wire :cdc_dbg_req_type, 8
  wire :cdc_dbg_req_code, 8
  wire :cdc_dbg_setup_full, 1
  wire :cdc_dbg_setup_cnt,  3
  wire :cdc_dbg_dispatch_hit, 1
  wire :cdc_dbg_live_b0, 8
  wire :cdc_dbg_live_b1, 8
  wire :cdc_dbg_descr_active, 1
  wire :cdc_dbg_indone, 1
  wire :cdc_dbg_heartbeat, 8
  wire :cdc_dbg_ep0_mirror, 2

  # --- Same-cycle coincidence gauges (the 'correct logic, wrong result' probe) ---
  # Each sticky bit asserts ONLY if its whole condition is true in ONE cycle —
  # unlike the other latches which each fire on whatever cycle their own signal
  # happened. This distinguishes 'preconditions never align in the same cycle'
  # from 'set then clobbered the same cycle'.
  wire :lat_coin_dispatch, 1, init: 0   # pkt_end & ep0 & setup & req==0x0005 ALL in one cycle
  wire :lat_coin_clobber,  1, init: 0   # ep_in_done true the SAME cycle the dispatch guard is
  # Gauge 1: ep0_state captured the cycle AFTER a confirmed dispatch coincidence.
  #   =2 -> the write DID land (then something clears it later); =0 -> the write
  #   never won the ep0_state mux at all.
  wire :coin_seen,     1, init: 0   # 1-cycle pipeline: a CD coincidence happened last cycle
  wire :lat_ep0_after, 2, init: 0   # ep0_state sampled the cycle after that coincidence
  # Gauge 2: which COMPETING ep0_state writer fires the same cycle as dispatch.
  wire :lat_coin_descr,  1, init: 0   # descriptor-stream branch active same cycle as dispatch
  # Gauge 3: top-level shadow of what ep0_state SHOULD become vs what it is.
  wire :lat_shadow_set,  1, init: 0   # shadow logic said 'ep0_state should be 2' at a dispatch
  # Inside-the-CDC probes:
  wire :lat_hb_moved,    1, init: 0   # CDC heartbeat EVER != 0  -> the CDC IS clocking
  wire :lat_mirror,      2, init: 0   # sticky max of the CDC-internal ep0_state mirror
  # Post-address enumeration progress:
  wire :lat_getdesc,     1, init: 0   # a GET_DESCRIPTOR (0x80,0x06) was EVER dispatched
  wire :lat_descrun,     1, init: 0   # the descriptor-stream branch EVER ran (ep0_state==1)
  wire :lat_setcfg,      1, init: 0   # a SET_CONFIGURATION (0x00,0x09) was EVER dispatched
  # Upstream: did a device-to-host SETUP (b0=0x80) ever reach the CDC's decode at
  # ALL? Distinguishes 'host never sends GET_DESCRIPTOR to us' from 'CDC sees it
  # but the dispatch/decode drops it'.
  wire :lat_saw_b0_80,   1, init: 0   # cdc_dbg_req_type == 0x80 ever seen at a dispatch
  wire :lat_last_b0,     8, init: 0   # the last setup_b0 the dispatch saw (any request)
  # US1 command-channel localizer gauges (to debug the reset-over-US1 path):
  wire :lat_us1_rx,      1, init: 0   # a byte was EVER received on the US1 command UART
  wire :lat_cmd_reset,   1, init: 0   # a 'R' (0x52) re-enum command was EVER decoded
  # Re-enum observation now comes from Hw.ReEnum's reset-SURVIVABLE reenum_count
  # output (see :reenum_count wire above) instead of a top-level rst-gated latch,
  # which was self-blinding (frozen during the very reset window it observed).
  # US1 RX liveness: is `valid` stuck high, or does it pulse per byte?
  wire :us1_valid_live,    1            # comb mirror of us1_rx_valid (live)
  wire :us1_rx_edges,      4, init: 0   # saturating count of us1_rx_valid RISING edges
  # --- TX-CHAIN localizers (the capture proved the device transmits NOTHING
  # valid on the wire; these pin WHICH link of SIE-serialize -> PHY-encode ->
  # pad-drive fails). All read already-exposed top signals; no PHY edits. ---
  wire :lat_sie_txpeak, 3, init: 0   # sticky MAX of usb_tx_state (SIE TX FSM: 0 idle..5 eop)
  wire :lat_phy_txvalid, 1, init: 0  # phy_tx_valid EVER high (SIE -> PHY bit handoff fired)
  wire :lat_phy_txactive, 1, init: 0 # _phy_tx_active EVER high (PHY TX FSM left idle)
  wire :lat_phy_txen,    1, init: 0  # phy_tx_en EVER high (PHY asserted pad output-enable)
  wire :lat_pad_toggle,  1, init: 0  # dp_tx==0 OR dn_tx==1 EVER (pads ever LEFT J-idle -> real drive)
  # --- TX-WAVEFORM capture: record the FIRST transmitted packet's symbols so we
  # can read what we ACTUALLY emit (SYNC/PID/EOP) vs a correct ACK. One
  # {dp_tx,dn_tx} symbol per bit, sampled mid-bit via the PHY's dbg_tx_midbit
  # strobe. Captures the first packet then FREEZES (tx_cap_done) and holds. ---
  wire :phy_tx_midbit, 1             # PHY dbg_tx_midbit strobe (one pulse per TX bit)
  wire :tx_cap,     48, init: 0      # 24 symbols x 2 bits (dp,dn), oldest in high bits
  wire :tx_cap_cnt,  5, init: 0      # symbols captured this packet (0..24)
  wire :tx_cap_done, 1, init: 0      # a full first-packet capture is frozen
  wire :txen_d,      1, init: 0      # registered phy_tx_en (edge detect)
  # --- TURNAROUND timing: cycles from RX-EOP (phy_rx_se0) to our TX-start
  # (phy_tx_en rising). USB FS requires the device response within ~2-7.5 bit
  # times = 8..30 cycles @48MHz. If turn_val >> 30, the ACK is generated but too
  # LATE (a latency bug in the RX->TX handoff); if it's healthy yet the wire
  # still shows nothing, the fault is electrical/pad. Captures the FIRST
  # turnaround, then freezes. ---
  wire :turn_active, 1,  init: 0     # currently timing a turnaround
  wire :turn_cnt,   14,  init: 0     # cycles since last RX-EOP
  wire :turn_val,   14,  init: 0     # captured EOP->TX-start latency (cycles)
  wire :turn_done,   1,  init: 0     # sticky: first turnaround measured

  # --- GET_DESCRIPTOR completion oracle (repurposes the TA display field) ---
  # Built ENTIRELY from already-exposed signals; localizes why descriptor IN
  # packets are ACKed (indone climbs) yet the host never configures us (CF=0).
  # Packed into desc_oracle (shown as TA<4hex>):
  #   [0]=data0_seen [1]=data1_seen [5:2]=ep0_in_cnt [6]=out_ep0_seen [7]=descdone
  # done bit (after TA hex) = data0_seen AND data1_seen (DATA0/DATA1 alternates).
  wire :o_data0,     1,  init: 0   # a descriptor IN packet carried DATA0 (0xC3)
  wire :o_data1,     1,  init: 0   # a descriptor IN packet carried DATA1 (0x4B)
  wire :o_ep0in_cnt, 4,  init: 0   # EP0 IN completions host ACKed (saturating)
  wire :o_out_ep0,   1,  init: 0   # a non-setup OUT@EP0 arrived (control-read STATUS stage)
  wire :o_descdone,  1,  init: 0   # descriptor data stage completed (ep0_state 1->2)
  wire :o_ep0_prev,  2,  init: 0   # prev cdc_ep0_state, for the 1->2 edge
  wire :o_req_dev,   1,  init: 0   # host requested the DEVICE descriptor
  wire :o_req_cfg,   1,  init: 0   # host requested the CONFIG descriptor
  wire :o_req_big,   1,  init: 0   # host requested >64 bytes (needs multi-packet)
  wire :cdc_dbg_req_valhi, 8
  wire :cdc_dbg_req_len7,  7
  wire :cdc_dbg_fb0,       8
  wire :cdc_dbg_fb1,       8
  wire :desc_oracle,14
  wire :desc_odone,  1
  wire :cdc_ep0_loaded, 1
  wire :cdc_ep1_loaded, 1
  wire :normal_led,     8

  # SIE internal state for diagnostics
  wire :usb_rx_state,        2
  wire :usb_tx_state,        3
  wire :usb_send_handshake,  1
  wire :usb_dbg_accept,      1
  wire :usb_dbg_txreq,       1

  # --- Hardware TX-arm oracle: sticky latches on the SETUP -> TX-arm chain ---
  # phy_dp_tx is FLAT on real hardware (device never transmits), while the host
  # sends SETUP+DATA0 forever. These latches capture how far ONE packet gets
  # before the transmit chain fails to arm. Routed to analyzer probe pins below.
  # Latched high on first occurrence, held forever (no clear) so a single capture
  # shows the deepest stage reached.
  wire :lat_rx_active,  1, init: 0   # PHY saw a packet
  wire :lat_pkt_end,    1, init: 0   # a SETUP/OUT DATA passed CRC16 (ACK precondition)
  wire :lat_accept,     1, init: 0   # a token passed CRC5 + addr-match
  wire :lat_tx_ran,     1, init: 0   # TX FSM left idle (device tried to transmit)
  wire :lat_hsk,        1, init: 0   # send_handshake EVER armed (accept->TX handoff)
  wire :lat_txreq,      1, init: 0   # tx_req EVER armed (IN token -> DATA transmit, not just ACK)
  wire :lat_epload,     1, init: 0   # CDC EVER loaded an EP IN buffer (descriptor ready to send)
  wire :lat_epout,      1, init: 0   # SIE EVER delivered an ep_out byte to the CDC
  wire :lat_setup,      1, init: 0   # an ep_out packet-end was EVER flagged SETUP
  # Snapshot of the CDC's decoded SETUP request (bmRequestType,bRequest) latched
  # at the setup packet-end — shows what the dispatch hdl_case actually saw.
  wire :lat_reqtype,    8, init: 0
  wire :lat_reqcode,    8, init: 0
  wire :lat_ep0moved,   1, init: 0   # CDC ep0_state EVER left idle (dispatch ran)
  wire :lat_setupfull,  1, init: 0   # CDC EVER accumulated all 8 SETUP bytes
  wire :lat_setupcnt,   3, init: 0   # peak SETUP byte count reached
  wire :lat_epout_ep,   4, init: 0   # ep_out_ep value seen at the setup packet-end
  wire :lat_dispatch,   1, init: 0   # CDC dispatch guard (ep==0 & setup) EVER true at pkt_end
  wire :lat_liveb0,     8, init: 0   # setup_b0 as the dispatch case actually saw it
  wire :lat_liveb1,     8, init: 0   # setup_b1 as the dispatch case actually saw it

  # --- PHY front-end diagnostics (computed at TOP LEVEL from the raw bus) ---
  # rx_active never rises on HW though gp0/gn0 (raw dp_diff/dn_raw) toggle. A K symbol
  # (the idle->detect trigger inside the PHY) needs D+ low AND D- high. Rather than
  # instrument the PHY's internal filtered signals (which perturbs its timing), we
  # compute the same K test here from the already-exposed raw dp_diff/dn_raw. This is
  # a pure passive top-level observer — it cannot affect the PHY or enumeration.
  # NOTE: named rawk_live / rawdnhigh_live (not raw_k / raw_dn_high) to avoid
  # colliding with the HealthReport instance's `raw_k` input port — instance port
  # names share the parent signal namespace during binding, so a top wire with
  # the same name as a connected instance port gets clobbered (its comb assign
  # silently retargets to the connected signal). See E020 hardening.
  wire :rawk_live,      1   # live: raw K symbol (dp_diff==0 and dn_raw==1)
  wire :rawdnhigh_live, 1   # live: raw D- high (dn_raw==1)
  wire :raw_se0,        1   # live: raw SE0 (dp_diff==0 and dn_raw==0) — bus-reset probe
  wire :usb_reset,      1, init: 0   # REGISTERED: SE0 held >= threshold -> USB bus reset (SE0 gauge only now)
  # --- Post-address RX / SIE address-match oracle ---
  wire :sie_rxaddr,     7   # address field of the last token the SIE decoded
  wire :sie_tokfail,    2   # last token outcome: 0=accept 1=crc5-fail 2=addr-mismatch
  wire :sie_tokdone,    1   # 1-cycle strobe: a token finished decoding
  wire :lat_peakaddr,   7, init: 0   # peak token addr the host has used (08 => addresses us at 8)
  wire :lat_tok8_seen,  1, init: 0   # a token to addr 8 was EVER decoded (host talks to us at 8)
  wire :lat_acc8,       1, init: 0   # a token was EVER accepted at addr 8 (addr-match WORKS at 8)
  wire :lat_tok8_rej,   1, init: 0   # a token to addr 8 was EVER rejected (addr-match FAILS at 8)
  wire :lat_tok_any,    1, init: 0   # any token EVER decoded (post-reset liveness)
  # --- SET_ADDRESS status-stage audit ---
  wire :sie_in_ep0,     1            # strobe: host IN@EP0 (status-IN request) accepted
  wire :devaddr_d,      7, init: 0   # registered prev dev_addr (rising-edge detect)
  wire :cnt_adopt,      4, init: 0   # dev_addr 0->nonzero adoptions (saturating)
  wire :cnt_indone,     4, init: 0   # ep_in_done pulses = ACKs after our IN (saturating)
  wire :cnt_inep0,      4, init: 0   # IN@EP0 status requests accepted (saturating)
  wire :cnt_nak,        4, init: 0   # ep_in_nak pulses = we NAKed an IN (no data loaded) (saturating)
  wire :lat_raw_k,      1, init: 0   # sticky: a raw K was EVER seen
  wire :lat_dn_high,    1, init: 0   # sticky: raw D- was EVER high

  # D+ tristate — TX drive + RX readback via dp_diff
  # Using single-ended D15 readback for dp_diff (not LVCMOS33D E16):
  # During SE0, LVCMOS33D sees D+=D-=0V (differential=0) → undefined output.
  # Single-ended D15 readback sees 0V → reliably 0. SE0 detection requires this.
  tristate :dp_buf,
    io:     :usb_fpga_bd_dp,
    output: :phy_dp_tx,
    enable: :phy_tx_en,
    input:  :dp_diff

  # D- tristate — TX drive + SE0 detection via dn_raw readback
  tristate :dn_buf,
    io:     :usb_fpga_bd_dn,
    output: :phy_dn_tx,
    enable: :phy_tx_en,
    input:  :dn_raw

  # PLL — 48 MHz primary, second output unused
  instance :pll, ULX3S.PLL,
    CLKOP_DIV:    9,
    CLKOS_DIV:    2,
    CLKOP_CPHASE: 8,
    CLKOS_CPHASE: 1,
    clk_in:       :clk_25mhz,
    clk_out0:     :clk_48,
    clk_out1:     :_clk_unused,
    locked:       :pll_locked,
    phase_dir:    0,
    phase_step:   0

  # Self-contained reset generator + re-enumeration controller (reset_style:
  # :none, so it can't be gated by the rst it produces). Owns BOTH the power-on
  # reset hold AND re-enum: a trigger (btn1 held, or a 'R' command over US1)
  # drops the D+ pullup for ~50 ms (host sees unplug) and asserts rst for the
  # same window, so the host re-runs enumeration on a freshly-reset device.
  # Replaces the old ResetSync + rst_arm indirection. See Hw.ReEnum.
  instance :reset_gen, Hw.ReEnum,
    HOLD_CYCLES: 2_400_000,   # ~50 ms @ 48 MHz (also the power-on settle)
    clk:        :clk_48,
    pll_locked: :pll_locked,
    btn:        :btn1_level,
    cmd_pulse:  :us1_cmd_reset,
    rst:        :rst,
    pu_drop:    :reenum_pu_drop,
    reenum_count: :reenum_count

  # US1 host->FPGA UART receiver @ 9600 8N1 on ftdi_txd (site M1). Decodes the
  # in-band command byte. Held in normal reset (rst) so it re-arms cleanly after
  # a re-enum window; commands issued during the ~50 ms window are ignored.
  instance :us1_rx, Hw.UART.RX,
    CLK_FREQ:  48_000_000,
    BAUD_RATE: 9_600,
    clk:       :clk_48,
    rst:       :rst,
    rxd:       :ftdi_txd,
    data:      :us1_rx_data,
    valid:     :us1_rx_valid,
    ready:     :us1_rx_ready

  comb do
    gn12           = 0
    usb_fpga_pu_dn = 0

    # D+ pullup: the PHY holds it high (device present); the re-enum controller
    # forces it LOW during a re-enum window so the host sees an unplug. This is
    # the ONLY thing that makes the host re-run enumeration — the PHY drives pu=1
    # unconditionally, so a reset alone would not disconnect us.
    usb_fpga_pu_dp = phy_pu and bnot(reenum_pu_drop)

    # btn1 is active-high (PULLMODE=DOWN: idle 0, pressed 1). Use it directly as a
    # level trigger for the re-enum controller (held-press keeps the window armed).
    btn1_level = btn1

    # US1 command decode. The UART RX HOLDS `valid` high until `ready` is acked,
    # so a combinational `cmd = valid and data=='R'` would stay high for MANY
    # cycles — which pinned the re-enum hold counter at 0 (reenum_active stuck
    # high, never completing its window, proven on silicon). Instead:
    #   - us1_rx_is_r: combinational "a valid 'R' is present"
    #   - us1_cmd_reset: a true 1-CYCLE pulse on the RISING edge of valid&'R'
    #     (valid now high, was low last cycle) — fires exactly once per byte.
    #   - us1_rx_ready: ack every valid byte so the RX re-arms for the next.
    us1_rx_is_r   = us1_rx_valid and (us1_rx_data == 0x52)
    us1_cmd_reset = us1_rx_is_r and bnot(us1_valid_d)
    us1_rx_ready  = us1_rx_valid
    us1_valid_live = us1_rx_valid   # live mirror for the dashboard

    cdc_ep0_loaded = sie_ep_in_loaded and sie_ep_in_ep == 0
    cdc_ep1_loaded = sie_ep_in_loaded and sie_ep_in_ep == 1

    # Raw K-symbol detection (top-level, from the raw bus — does NOT touch the PHY):
    # a K is D+ low AND D- high. If the host is signalling, raw_k must pulse; if
    # raw D- never goes high, no K exists and the PHY can never leave idle.
    rawdnhigh_live = (dn_raw == 1)
    rawk_live      = (dp_diff == 0) and (dn_raw == 1)
    raw_se0        = (dp_diff == 0) and (dn_raw == 0)

    # Repurposed TA field: pack the GET_DESCRIPTOR completion oracle.
    #   [0]=data0 [1]=data1 [5:2]=ep0_in_cnt [6]=out_ep0 [7]=descdone
    desc_oracle = {0[2..0], o_req_big, o_req_cfg, o_req_dev, o_descdone, o_out_ep0, o_ep0in_cnt, o_data1, o_data0}
    desc_odone  = o_data0 and o_data1

    # usb_reset (registered in the SE0 gauge block) feeds the CDC's usb_reset input,
    # which clears ONLY the enum registers (addr 0, unconfigured) while the CDC keeps
    # clocking. NOT wired to any module reset -- gating the SIE/CDC module reset with
    # this froze the design and killed the dashboard; the targeted clear does not.

    # Logic analyzer probes — raw-bus K-detect oracle (see header comment for mapping)
    gp0 = dp_diff                  # host D+ raw bus (trigger)
    gn0 = dn_raw                   # host D- raw bus
    gp1 = rawdnhigh_live           # live: raw D- high
    gn1 = rawk_live                # live: raw K symbol (D+ low & D- high)
    gp2 = lat_dn_high              # sticky: raw D- was EVER high  <-- KEY
    gn2 = lat_raw_k                # sticky: a raw K was EVER seen  <-- KEY
    gp3 = phy_rx_active            # live: PHY declared a packet (should follow K)
    gn3 = usb_rx_state[0..0]       # live: PHY RX state LSB (context)

    normal_led = {
      pll_locked,
      sie_ep_out_pkt_end,
      sie_ep_out_valid,
      sie_ep_out_setup,
      cdc_rx_valid,
      cdc_tx_valid,
      cdc_dev_state[1..1],
      cdc_dev_state[0..0]
    }

  end

  # --- Hardware TX-arm oracle: sticky-latch capture ---
  # Each latch goes high the first time its stage fires and is held forever (no
  # clear), so a single analyzer capture shows the deepest stage the SETUP->TX-arm
  # chain reached. Cleared only by rst (power-up / bus reset hold).
  on :clk_48 do
    if rst do
      lat_rx_active = 0
      lat_pkt_end   = 0
      lat_accept    = 0
      lat_tx_ran    = 0
      lat_raw_k     = 0
      lat_dn_high   = 0
      lat_hsk       = 0
      lat_txreq     = 0
      lat_epload    = 0
      lat_epout     = 0
      lat_setup     = 0
      lat_reqtype   = 0
      lat_reqcode   = 0
      lat_ep0moved  = 0
      lat_setupfull = 0
      lat_setupcnt  = 0
      lat_epout_ep  = 0
      lat_dispatch  = 0
      lat_liveb0    = 0
      lat_liveb1    = 0
      lat_coin_dispatch = 0
      lat_coin_clobber  = 0
      coin_seen         = 0
      lat_ep0_after     = 0
      lat_coin_descr    = 0
      lat_shadow_set    = 0
      lat_hb_moved      = 0
      lat_mirror        = 0
      lat_getdesc       = 0
      lat_descrun       = 0
      lat_setcfg        = 0
      lat_saw_b0_80     = 0
      lat_last_b0       = 0
      us1_valid_d       = 0
      us1_rx_edges      = 0
      lat_sie_txpeak    = 0
      lat_phy_txvalid   = 0
      lat_phy_txactive  = 0
      lat_phy_txen      = 0
      lat_pad_toggle    = 0
      tx_cap            = 0
      tx_cap_cnt        = 0
      tx_cap_done       = 0
      lat_peakaddr      = 0
      lat_tok8_seen     = 0
      lat_acc8          = 0
      lat_tok8_rej      = 0
      lat_tok_any       = 0
      cnt_adopt         = 0
      cnt_indone        = 0
      cnt_inep0         = 0
      cnt_nak           = 0
      devaddr_d         = 0
      txen_d            = 0
      turn_active       = 0
      turn_cnt          = 0
      turn_val          = 0
      turn_done         = 0
      usb_reset         = 0
      o_data0           = 0
      o_data1           = 0
      o_ep0in_cnt       = 0
      o_out_ep0         = 0
      o_descdone        = 0
      o_ep0_prev        = 0
      o_req_dev         = 0
      o_req_cfg         = 0
      o_req_big         = 0
    else
      if phy_rx_active,      do: lat_rx_active = 1
      if sie_ep_out_pkt_end, do: lat_pkt_end   = 1
      if usb_dbg_accept,     do: lat_accept    = 1
      if usb_tx_state != 0,  do: lat_tx_ran    = 1
      if usb_send_handshake, do: lat_hsk       = 1
      if usb_dbg_txreq,      do: lat_txreq     = 1
      if sie_ep_in_loaded,   do: lat_epload    = 1
      if sie_ep_out_valid,   do: lat_epout     = 1
      if sie_ep_out_pkt_end and sie_ep_out_setup do
        lat_setup    = 1
        lat_reqtype  = cdc_dbg_req_type
        lat_reqcode  = cdc_dbg_req_code
        lat_epout_ep = sie_ep_out_ep
      end
      if cdc_dbg_dispatch_hit do
        lat_dispatch = 1
        lat_liveb0   = cdc_dbg_live_b0
        lat_liveb1   = cdc_dbg_live_b1
      end
      # Same-cycle coincidence gauges: the whole condition must hold in ONE cycle.
      # coin_dispatch: the CDC dispatch guard fired AND the decoded request is
      # exactly SET_ADDRESS (0x00,0x05) on the SAME cycle. If this stays 0 while
      # lat_dispatch=1 and Q=0005, the guard and the matching bytes never align.
      if cdc_dbg_dispatch_hit and cdc_dbg_req_type == 0 and cdc_dbg_req_code == 5 do
        lat_coin_dispatch = 1
      end
      # coin_clobber: ep_in_done (which resets ep0_state->0) is true the SAME cycle
      # the dispatch guard is — i.e. the dispatch's ep0_state=2 is overwritten to 0
      # in the very cycle it's set.
      if cdc_dbg_dispatch_hit and sie_ep_in_done do
        lat_coin_clobber = 1
      end

      # --- Gauge 1: sample ep0_state the cycle AFTER a confirmed coincidence ---
      # coin_seen pipelines the SET_ADDRESS coincidence by one cycle; on that next
      # cycle we snapshot ep0_state. If the dispatch's ep0_state=2 committed, this
      # reads 2; if the write lost the mux, it reads 0.
      if coin_seen and lat_ep0_after == 0 do
        lat_ep0_after = cdc_ep0_state
      end
      coin_seen = cdc_dbg_dispatch_hit and cdc_dbg_req_type == 0 and cdc_dbg_req_code == 5

      # --- Gauge 2: competing writer (descriptor-stream) same cycle as dispatch ---
      if cdc_dbg_dispatch_hit and cdc_dbg_descr_active do
        lat_coin_descr = 1
      end

      # --- Gauge 3: top-level shadow of the intended ep0_state write ---
      # The dispatch SHOULD set ep0_state=2 whenever the guard fires with a
      # request that maps to a state-2 arm (SET_ADDRESS/SET_CONFIG/SET_CLS). Latch
      # that intent; compare against MV (actual ep0_state ever != 0).
      if cdc_dbg_dispatch_hit and cdc_dbg_req_type == 0 and cdc_dbg_req_code == 5 do
        lat_shadow_set = 1
      end

      # --- Inside-the-CDC probes ---
      # If the CDC heartbeat is ever nonzero, the CDC's own clock+reset are live.
      if cdc_dbg_heartbeat != 0, do: lat_hb_moved = 1
      # Sticky-hold the CDC-internal ep0_state mirror. If this hits 2 while the
      # ep0_state OUTPUT (lat_ep0moved/MV) stays 0, the write landed internally
      # but the output net is aliased.
      if cdc_dbg_ep0_mirror > lat_mirror, do: lat_mirror = cdc_dbg_ep0_mirror

      # --- Post-address enumeration progress ---
      if cdc_dbg_dispatch_hit and cdc_dbg_req_type == 0x80 and cdc_dbg_req_code == 0x06 do
        lat_getdesc = 1
      end
      if cdc_dbg_dispatch_hit and cdc_dbg_req_type == 0 and cdc_dbg_req_code == 0x09 do
        lat_setcfg = 1
      end
      if cdc_dbg_descr_active, do: lat_descrun = 1
      if cdc_dbg_dispatch_hit do
        lat_last_b0 = cdc_dbg_req_type
        if cdc_dbg_req_type == 0x80, do: lat_saw_b0_80 = 1
      end

      # US1 command-channel localizers: which stage of the reset-over-US1 path
      # actually fires. U1=1 means the on-chip UART received ANY byte on ftdi_txd;
      # CR=1 means a byte decoded as the 'R' re-enum command. Both are sticky here
      # (cleared by rst) — note a successful re-enum resets them too, so to catch a
      # working command watch for U1/CR flipping to 1 in the frame(s) just before
      # the reset dip. If U1 stays 0, the byte never reaches the FPGA/UART; if U1=1
      # but CR=0, it arrives but doesn't decode as 'R'.
      # Register previous us1_rx_valid for the rising-edge command pulse above.
      us1_valid_d = us1_rx_valid
      # Count RISING edges of us1_rx_valid (saturating at 15). If this stays 0
      # while U1=1, `valid` went high once and NEVER fell (stuck) — no discrete
      # bytes. If it climbs per 'R' sent, the UART is pulsing correctly and the
      # stuck-cmd_reset bug is elsewhere.
      if us1_rx_valid and bnot(us1_valid_d) and us1_rx_edges < 15 do
        us1_rx_edges = us1_rx_edges + 1
      end

      if us1_rx_valid,   do: lat_us1_rx    = 1
      if us1_cmd_reset,  do: lat_cmd_reset = 1

      if cdc_ep0_state != 0,     do: lat_ep0moved  = 1
      if cdc_dbg_setup_full,     do: lat_setupfull = 1
      if cdc_dbg_setup_cnt > lat_setupcnt, do: lat_setupcnt = cdc_dbg_setup_cnt
      # Raw-bus K-detect (computed from dp_diff/dn_raw, does not touch the PHY):
      if rawk_live,          do: lat_raw_k     = 1
      if rawdnhigh_live,     do: lat_dn_high   = 1

      # --- TX-CHAIN localizers (pipeline order; read on a single flash) ---
      # 1) How far did the SIE TX serializer get? Sticky MAX of usb_tx_state.
      if usb_tx_state > lat_sie_txpeak, do: lat_sie_txpeak = usb_tx_state
      # 2) Did the SIE ever hand a bit to the PHY?
      if phy_tx_valid,   do: lat_phy_txvalid  = 1
      # 3) Did the PHY TX FSM ever leave idle?
      if _phy_tx_active, do: lat_phy_txactive = 1
      # 4) Did the PHY ever assert the pad output-enable?
      if phy_tx_en,      do: lat_phy_txen     = 1
      # 5) Did the pads ever ACTUALLY leave J-idle (dp_tx=1,dn_tx=0)? A real
      #    transmission drives K (dp_tx=0) and/or SE0 (dn stays 0 but dp=0) and
      #    D- high. If this stays 0 while txen=1, the FSM enabled the driver but
      #    never changed the levels -> encoding/serialize stuck at J.
      if (phy_dp_tx == 0) or (phy_dn_tx == 1), do: lat_pad_toggle = 1

      # --- ADDRESS-MATCH oracle (repurposes the TC/tx_cap field) ---------------
      # The wall is post-address RX: after SET_ADDRESS (dev_addr=8) Q freezes at
      # 0005 and no GET_DESCRIPTOR is decoded. Hypothesis: the host addresses
      # tokens to addr 8 but our SIE address-match fails, so we go deaf at 8.
      # On each token-complete strobe from the SIE, update the sticky gauges:
      if sie_tokdone do
        lat_tok_any = 1
        if sie_rxaddr > lat_peakaddr, do: lat_peakaddr = sie_rxaddr
        if sie_rxaddr == 8 do
          lat_tok8_seen = 1
          if sie_tokfail == 0, do: lat_acc8     = 1   # accepted at addr 8 -> match WORKS
          if sie_tokfail != 0, do: lat_tok8_rej = 1   # token to 8 rejected -> match FAILS
        end
      end
      # --- SET_ADDRESS status-stage audit ---
      # cnt_inep0 = host status-IN requests we accepted; cnt_indone = ACKs we saw
      # after transmitting; cnt_adopt = times dev_addr went 0->nonzero. The tell:
      #   adopt>0 with inep0==0  => we adopt WITHOUT a host status IN (spurious).
      #   inep0>0 but indone<inep0 => host asks, we answer, host never ACKs (ZLP bad).
      #   inep0==indone==adopt (small) => sequence correct; desync is host-side.
      if sie_in_ep0     and cnt_inep0  < 15, do: cnt_inep0  = cnt_inep0  + 1
      if sie_ep_in_done and cnt_indone < 15, do: cnt_indone = cnt_indone + 1
      if sie_ep_in_nak  and cnt_nak    < 15, do: cnt_nak    = cnt_nak    + 1
      if dev_addr != 0 and devaddr_d == 0 and cnt_adopt < 15, do: cnt_adopt = cnt_adopt + 1
      devaddr_d = dev_addr
      # Pack into TC (12 hex): [3:0]=cnt_adopt [7:4]=cnt_indone [11:8]=cnt_inep0
      # [15:12]=cnt_nak. So many INs (inep0) with few ACKs (indone): if nak~=inep0
      # we're NAKing (ZLP not loaded); if nak~=0 we TX but host rejects (signal).
      tx_cap = {0[31..0], cnt_nak, cnt_inep0, cnt_indone, cnt_adopt}

      # --- PEAK SE0-RUN measurement (repurposed from turnaround, now proven
      # healthy). TA field = longest consecutive raw-bus SE0 run EVER seen (hex,
      # saturating 0x3FFF); the done bit after TA = an SE0 longer than any EOP
      # (>32 cyc) was seen = the host issued a bus RESET. EOP SE0 ~8 cyc; a USB
      # bus reset holds SE0 >=120 cyc (host drives ~10 ms). This confirms whether
      # the host resets us (and calibrates the reset-detector threshold sweep).
      # Count consecutive SE0 ONLY while the bus is idle (we are NOT driving it).
      # Gating on bnot(phy_tx_en) is critical: the DEVICE itself drives SE0 during
      # every EOP and during TX turnaround. Counting our own driven SE0 let
      # turn_cnt cross the bus-reset threshold spuriously, which fired usb_reset
      # mid-transaction and cleared the enum state -> the device NAKed the host's
      # in-flight IN, the host reset, and it spiralled into a re-address loop
      # (silicon: failing boots showed cnt_adopt=4, cnt_nak=7; passing boots
      # cnt_adopt=1, cnt_nak=0). Only HOST-driven, bus-idle SE0 is a real reset.
      if raw_se0 and bnot(phy_tx_en) do
        if turn_cnt < 16383, do: turn_cnt = turn_cnt + 1
      else
        turn_cnt = 0
      end
      if turn_cnt > turn_val, do: turn_val = turn_cnt
      if turn_val > 32,       do: turn_done = 1
      # Registered USB bus-reset flag: high once the live SE0 run crosses the
      # threshold, low as soon as SE0 ends. Drives the CDC's usb_reset input,
      # which clears the enum registers (addr 0, unconfigured) so we answer the
      # post-reset SET_ADDRESS as a fresh device. Threshold 128 cyc (~2.7 us @48M)
      # is WAY above an EOP's SE0 (~8 cyc) but well below a real host bus reset
      # (silicon showed a 478-cyc reset that the old 512 threshold MISSED, so the
      # device never returned to address 0 and stalled at DEV1/A07).
      usb_reset = turn_cnt >= 128

      txen_d = phy_tx_en

      # --- GET_DESCRIPTOR completion oracle latches (all from exposed signals) ---
      # Which DATA PID each descriptor IN packet carried (stream branch active).
      if cdc_dbg_descr_active and sie_ep_in_pid == 0xC3, do: o_data0 = 1
      if cdc_dbg_descr_active and sie_ep_in_pid == 0x4B, do: o_data1 = 1
      # EP0 IN completions the host ACKed (descriptor packets accepted).
      if sie_ep_in_done and sie_ep_in_ep == 0 and o_ep0in_cnt < 15, do: o_ep0in_cnt = o_ep0in_cnt + 1
      # Host OUT@EP0, non-setup = the control-read STATUS stage arrived.
      if sie_ep_out_pkt_end and sie_ep_out_ep == 0 and bnot(sie_ep_out_setup), do: o_out_ep0 = 1
      # Descriptor DATA stage completed: ep0_state 1 -> 2 (desc_remain hit 0).
      if o_ep0_prev == 1 and cdc_ep0_state == 2, do: o_descdone = 1
      o_ep0_prev = cdc_ep0_state
      # What the host asked for at each GET_DESCRIPTOR dispatch.
      if cdc_dbg_dispatch_hit and cdc_dbg_req_type == 0x80 and cdc_dbg_req_code == 0x06 do
        if cdc_dbg_req_valhi == 0x01, do: o_req_dev = 1
        if cdc_dbg_req_valhi == 0x02, do: o_req_cfg = 1
        if cdc_dbg_req_len7 > 64, do: o_req_big = 1
      end
    end
  end

  instance :phy, Hw.USB.FSPhy,
    clk_48mhz:   :clk_48,
    rst:         :rst,
    dp_diff:     :dp_diff,
    dn_raw:      :dn_raw,
    dp_tx:       :phy_dp_tx,
    dn_tx:       :phy_dn_tx,
    tx_en:       :phy_tx_en,
    pu:          :phy_pu,
    rx_valid:    :phy_rx_valid,
    rx_data:     :phy_rx_data,
    rx_se0:      :phy_rx_se0,
    rx_active:   :phy_rx_active,
    rx_bit0:     :phy_rx_bit0,
    rx_pid_done: :phy_rx_pid_done,
    tx_valid:    :phy_tx_valid,
    tx_data:     :phy_tx_data,
    tx_se0:      :phy_tx_se0,
    tx_ready:    :phy_tx_ready,
    tx_active:   :_phy_tx_active,
    dbg_tx_midbit: :phy_tx_midbit

  instance :sie, Hw.USB.SIE,
    clk_48mhz:       :clk_48,
    rst:             :rst,
    dev_addr:        :dev_addr,
    phy_rx_valid:    :phy_rx_valid,
    phy_rx_data:     :phy_rx_data,
    phy_rx_se0:      :phy_rx_se0,
    phy_rx_active:   :phy_rx_active,
    phy_rx_bit0:     :phy_rx_bit0,
    phy_tx_valid:    :phy_tx_valid,
    phy_tx_data:     :phy_tx_data,
    phy_tx_se0:      :phy_tx_se0,
    phy_tx_ready:    :phy_tx_ready,
    ep_out_data:     :sie_ep_out_data,
    ep_out_valid:    :sie_ep_out_valid,
    ep_out_ep:       :sie_ep_out_ep,
    ep_out_setup:    :sie_ep_out_setup,
    ep_out_pkt_end:  :sie_ep_out_pkt_end,
    ep_in_ep:        :sie_ep_in_ep,
    ep_in_pid:       :sie_ep_in_pid,
    ep_in_data:      :sie_ep_in_data,
    ep_in_valid:     :sie_ep_in_valid,
    ep_in_loaded:    :sie_ep_in_loaded,
    ep_in_ready:     :sie_ep_in_ready,
    ep_in_done:      :sie_ep_in_done,
    ep_in_nak:       :sie_ep_in_nak,
    rx_state_out:       :usb_rx_state,
    tx_state_out:       :usb_tx_state,
    send_handshake_out: :usb_send_handshake,
    dbg_accept_out:     :usb_dbg_accept,
    dbg_txreq_out:      :usb_dbg_txreq,
    dbg_rxaddr_out:     :sie_rxaddr,
    dbg_tokfail_out:    :sie_tokfail,
    dbg_tokdone_out:    :sie_tokdone,
    dbg_in_ep0_out:     :sie_in_ep0

  instance :cdc, Hw.USB.CDCSerial,
    clk_48mhz:       :clk_48,
    rst:             :rst,
    usb_reset:       :usb_reset,
    ep_out_data:     :sie_ep_out_data,
    ep_out_valid:    :sie_ep_out_valid,
    ep_out_ep:       :sie_ep_out_ep,
    ep_out_setup:    :sie_ep_out_setup,
    ep_out_pkt_end:  :sie_ep_out_pkt_end,
    ep_in_ep:        :sie_ep_in_ep,
    ep_in_pid:       :sie_ep_in_pid,
    ep_in_data:      :sie_ep_in_data,
    ep_in_valid:     :sie_ep_in_valid,
    ep_in_loaded:    :sie_ep_in_loaded,
    ep_in_ready:     :sie_ep_in_ready,
    ep_in_done:      :sie_ep_in_done,
    ep_in_nak:       :sie_ep_in_nak,
    dev_addr:        :dev_addr,
    rx_data:         :cdc_rx_data,
    rx_valid:        :cdc_rx_valid,
    rx_ready:        :cdc_rx_ready,
    tx_data:         :cdc_tx_data,
    tx_valid:        :cdc_tx_valid,
    tx_ready:        :cdc_tx_ready,
    dtr:             :dtr,
    rts:             :rts,
    dev_state:       :cdc_dev_state,
    ep0_state:       :cdc_ep0_state,
    dbg_req_type:    :cdc_dbg_req_type,
    dbg_req_code:    :cdc_dbg_req_code,
    dbg_setup_full:  :cdc_dbg_setup_full,
    dbg_setup_cnt:   :cdc_dbg_setup_cnt,
    dbg_dispatch_hit: :cdc_dbg_dispatch_hit,
    dbg_live_b0:     :cdc_dbg_live_b0,
    dbg_live_b1:     :cdc_dbg_live_b1,
    dbg_descr_active: :cdc_dbg_descr_active,
    dbg_indone:      :cdc_dbg_indone,
    dbg_heartbeat:   :cdc_dbg_heartbeat,
    dbg_ep0_mirror:  :cdc_dbg_ep0_mirror,
    dbg_req_valhi:   :cdc_dbg_req_valhi,
    dbg_req_len7:    :cdc_dbg_req_len7,
    dbg_fb0:         :cdc_dbg_fb0,
    dbg_fb1:         :cdc_dbg_fb1

  instance :uart_tx, Hw.UART.TX,
    CLK_FREQ:  48_000_000,
    BAUD_RATE: 115_200,
    clk:       :clk_48,
    rst:       :rst,
    data:      :cdc_rx_data,
    valid:     :cdc_rx_valid,
    ready:     :cdc_rx_ready,
    txd:       :wifi_rxd

  instance :uart_rx, Hw.UART.RX,
    CLK_FREQ:  48_000_000,
    BAUD_RATE: 115_200,
    clk:       :clk_48,
    rst:       :rst,
    rxd:       :wifi_txd,
    data:      :cdc_tx_data,
    valid:     :cdc_tx_valid,
    ready:     :cdc_tx_ready

  instance :prog, Hw.ESP32.ProgCtrl,
    CLK_FREQ:      48_000_000,
    RESET_HOLD_US: 100,
    clk:           :clk_48,
    rst:           :rst,
    dtr:           :dtr,
    rts:           :rts,
    esp_en:        :wifi_en,
    esp_gpio0:     :wifi_gpio0

  instance :diag, Hw.Diag.Display,
    clk:             :clk_48,
    rst:             :rst,
    btn_diag:        :btn2,
    normal_led:      :normal_led,
    dev_state:       :cdc_dev_state,
    ep0_state:       :cdc_ep0_state,
    ep0_loaded:      :cdc_ep0_loaded,
    ep1_loaded:      :cdc_ep1_loaded,
    ep_in_done:      :sie_ep_in_done,
    ep_in_nak:       :sie_ep_in_nak,
    ep_out_pkt_end:  :sie_ep_out_pkt_end,
    ep_out_valid:    :sie_ep_out_valid,
    ep_out_setup:    :sie_ep_out_setup,
    ep_in_ready:     :sie_ep_in_ready,
    phy_rx_active:   :phy_rx_active,
    phy_rx_valid:    :phy_rx_valid,
    phy_rx_se0:      :phy_rx_se0,
    phy_tx_valid:    :phy_tx_valid,
    sie_rx_state:      :usb_rx_state,
    sie_tx_state:      :usb_tx_state,
    sie_send_handshake: :usb_send_handshake,
    led:               :led

  # Serial diagnostic reporter (US1 FTDI). Streams six sticky latches as an ASCII
  # line `b0b1b2b3b4b5\r\n` at 115200 8N1 so the host can read the device's
  # internal state over /dev/cu.usbserial-* — no logic analyzer needed.
  # Column order (b0..b5):
  #   b0 = lat_dn_high   (raw D- was EVER high)
  #   b1 = lat_raw_k     (a raw K was EVER seen)
  #   b2 = lat_rx_active (PHY EVER declared a packet)
  #   b3 = lat_pkt_end   (a packet EVER passed CRC16)
  #   b4 = lat_accept    (a token EVER accepted)
  #   b5 = lat_tx_ran    (TX FSM EVER ran)
  # Serial diagnostic reporter (US1 FTDI) @ 9600 baud. Streams six sticky latches
  # as an ASCII line `b0b1b2b3b4b5\r\n` so the host reads device state over
  # /dev/cu.usbserial-*. 9600 (not 115200) avoids the FTDI RX-FIFO overrun that
  # stalls the link at high rates. Column order (b0..b5):
  #   b0 = lat_dn_high   (raw D- was EVER high)
  #   b1 = lat_raw_k     (a raw K was EVER seen)      <- THE PHY QUESTION
  #   b2 = lat_rx_active (PHY EVER declared a packet)
  #   b3 = lat_pkt_end   (a packet EVER passed CRC16)
  #   b4 = lat_accept    (a token EVER accepted)
  #   b5 = lat_tx_ran    (TX FSM EVER ran)
  # Full labeled health dashboard (US1 FTDI) @ 9600 baud. Streams EVERY
  # instrumentation point — sticky pipeline latches AND live FSM state — as one
  # self-documenting ASCII line so the host reads the entire enumeration state
  # over /dev/cu.usbserial-* at a glance:
  #   PLLp RSTr | DNHa RAWKk RXx PKTe ACCc TXt | RXs TXu DEVd EP0 e0 ADDRhh DONEn NAKm
  # 9600 (not 115200) avoids the FTDI RX-FIFO overrun that stalls at high rates.
  instance :health_report, Hw.Diag.HealthReport,
    BYTE_CYCLES: 60_000,   # 9600 baud = 5000 cyc/bit; 12 bit-times + margin
    GAP_CYCLES:  480_000,  # ~10 ms between lines
    clk:        :clk_48,
    rst:        :rst,
    pll_locked: :pll_locked,
    in_rst:     :rst,
    dn_high:    :lat_dn_high,
    raw_k:      :lat_raw_k,
    rx_active:  :lat_rx_active,
    pkt_end:    :lat_pkt_end,
    accept:     :lat_accept,
    tx_ran:     :lat_tx_ran,
    hsk:        :lat_hsk,
    txreq:      :lat_txreq,
    epload:     :lat_epload,
    epout:      :lat_epout,
    setup:      :lat_setup,
    reqtype:    :lat_reqtype,
    reqcode:    :lat_reqcode,
    ep0moved:   :lat_ep0moved,
    setupfull:  :lat_setupfull,
    setupcnt:   :lat_setupcnt,
    epoutep:    :lat_epout_ep,
    dispatch:   :lat_dispatch,
    liveb0:     :cdc_dbg_fb0,
    liveb1:     :cdc_dbg_fb1,
    rx_state:   :usb_rx_state,
    tx_state:   :usb_tx_state,
    dev_state:  :cdc_dev_state,
    ep0_state:  :cdc_ep0_state,
    dev_addr:   :dev_addr,
    ep_in_done: :sie_ep_in_done,
    ep_in_nak:  :sie_ep_in_nak,
    coin_disp:  :lat_coin_dispatch,
    coin_clob:  :lat_coin_clobber,
    ep0after:   :lat_ep0_after,
    coindescr:  :lat_coin_descr,
    shadowset:  :lat_shadow_set,
    hbmoved:    :lat_hb_moved,
    mirror:     :lat_mirror,
    getdesc:    :lat_getdesc,
    descrun:    :lat_descrun,
    setcfg:     :lat_setcfg,
    sawb080:    :lat_saw_b0_80,
    lastb0:     :lat_last_b0,
    us1rx:      :lat_us1_rx,
    cmdrst:     :lat_cmd_reset,
    reactive:   :reenum_count,
    uvlive:     :us1_valid_live,
    rxedges:    :us1_rx_edges,
    txpeak:     :lat_sie_txpeak,
    txvalid:    :lat_phy_txvalid,
    txactive:   :lat_phy_txactive,
    txen:       :lat_phy_txen,
    padtog:     :lat_pad_toggle,
    txcap:      :tx_cap,
    txcapcnt:   :tx_cap_cnt,
    txcapdone:  :tx_cap_done,
    turnval:    :desc_oracle,
    turndone:   :desc_odone,
    txd:        :ftdi_rxd
end
