defmodule Hw.CORDIC do
  @moduledoc """
  CORDIC (COordinate Rotation DIgital Computer) processor.

  Iterative algorithm for computing trigonometric functions using only
  shifts and adds. Converges ~1 bit per iteration.

  ## Modes

  - `:rotation` - Given angle θ, compute (cos θ, sin θ)
    - Input: x=K, y=0, z=θ (where K = 1/gain ≈ 0.607)
    - Output: x=cos(θ), y=sin(θ), z≈0

  - `:vectoring` - Given (x,y), compute magnitude and phase
    - Input: x=x, y=y, z=0
    - Output: x=mag*K, y≈0, z=atan2(y,x)

  ## Parameters

  - `WIDTH` - Bit width of x, y, z (default: 16)
  - `ITERATIONS` - Number of CORDIC iterations (default: WIDTH)
  - `MODE` - 0 for rotation, 1 for vectoring (directly maps to port but can parameterize external logic)

  ## Ports

  - `clk` - Clock
  - `start` - Pulse high to begin computation
  - `mode` - 0=rotation, 1=vectoring
  - `x_in`, `y_in`, `z_in` - Inputs (signed)
  - `x_out`, `y_out`, `z_out` - Outputs (signed)
  - `done` - High when result valid

  ## Usage

      # Rotation mode: compute sin/cos
      instance :cordic, Hw.CORDIC, WIDTH: 16

      # In your logic:
      # Set x_in = 0x4DBA (≈0.607 in Q15, the CORDIC gain constant)
      # Set y_in = 0
      # Set z_in = angle (in radians, scaled to fit WIDTH bits)
      # Pulse start
      # Wait for done
      # Read cos(angle) from x_out, sin(angle) from y_out

  ## Implementation

  This is a serial/iterative implementation using WIDTH cycles.
  For higher throughput, consider pipelining (one iteration per stage).

  The atan lookup table is generated at compile time.
  """

  use Hw.Component

  param :WIDTH, default: 16
  param :ITERATIONS, default: 16  # Usually same as WIDTH

  clock :clk
  input :start, 1
  input :mode, 1                    # 0=rotation, 1=vectoring
  input :x_in, WIDTH, signed: true
  input :y_in, WIDTH, signed: true
  input :z_in, WIDTH, signed: true
  output :x_out, WIDTH, signed: true
  output :y_out, WIDTH, signed: true
  output :z_out, WIDTH, signed: true
  output :done, 1

  # Internal registers
  wire :x, WIDTH, signed: true
  wire :y, WIDTH, signed: true
  wire :z, WIDTH, signed: true
  wire :iteration, clog2(ITERATIONS + 1)
  wire :running, 1

  # Atan lookup table (precomputed at compile time)
  # atan(2^-i) in radians, scaled to WIDTH bits
  # For 16-bit: atan(1)=0.785 rad -> 0x6488 (π/4 scaled)
  #
  # These are the values for 16 iterations at 16-bit width:
  # Generated by: for i <- 0..15, do: round(:math.atan(:math.pow(2, -i)) * 32768 / :math.pi)
  memory :atan_table, width: WIDTH, depth: 16, init: [
    0x6488,  # atan(2^0)  = 45.0°
    0x3B59,  # atan(2^-1) = 26.57°
    0x1F5B,  # atan(2^-2) = 14.04°
    0x0FEB,  # atan(2^-3) = 7.13°
    0x07FD,  # atan(2^-4) = 3.58°
    0x0400,  # atan(2^-5) = 1.79°
    0x0200,  # atan(2^-6) = 0.90°
    0x0100,  # atan(2^-7) = 0.45°
    0x0080,  # atan(2^-8) = 0.22°
    0x0040,  # atan(2^-9) = 0.11°
    0x0020,  # atan(2^-10)
    0x0010,  # atan(2^-11)
    0x0008,  # atan(2^-12)
    0x0004,  # atan(2^-13)
    0x0002,  # atan(2^-14)
    0x0001   # atan(2^-15)
  ]

  # Shifted values for current iteration
  wire :x_shift, WIDTH, signed: true
  wire :y_shift, WIDTH, signed: true
  wire :atan_val, WIDTH, signed: true

  # Direction of rotation
  wire :sigma, 1

  comb do
    # Arithmetic right shift by iteration count
    x_shift = shra(x, iteration)
    y_shift = shra(y, iteration)

    # Lookup atan value for current iteration
    atan_val = atan_table[iteration]

    # Determine rotation direction
    # Rotation mode: rotate toward z=0, so sigma = sign(z)
    # Vectoring mode: rotate toward y=0, so sigma = -sign(y)
    sigma = if mode == 0 do
      z[WIDTH - 1]  # Sign bit of z (1 if negative)
    else
      bnot(y[WIDTH - 1])  # Inverted sign bit of y
    end

    # Outputs
    x_out = x
    y_out = y
    z_out = z
    done = bnot(running)
  end

  on :clk do
    if start == 1 do
      # Load inputs and start
      x = x_in
      y = y_in
      z = z_in
      iteration = 0
      running = 1
    else
      if running == 1 do
        if iteration < ITERATIONS do
          # CORDIC iteration
          if sigma == 1 do
            # Rotate clockwise (negative angle)
            x = x + y_shift
            y = y - x_shift
            z = z + atan_val
          else
            # Rotate counter-clockwise (positive angle)
            x = x - y_shift
            y = y + x_shift
            z = z - atan_val
          end
          iteration = iteration + 1
        else
          # Done
          running = 0
        end
      end
    end
  end

  @doc """
  Calculate the CORDIC gain constant K for n iterations.

  K = ∏(1/√(1 + 2^(-2i))) for i = 0 to n-1

  For infinite iterations, K ≈ 0.6072529350088814

  To use rotation mode, pre-scale x_in by K (or post-scale outputs by 1/K).
  """
  def gain(iterations \\ 16) do
    Enum.reduce(0..(iterations - 1), 1.0, fn i, acc ->
      acc / :math.sqrt(1 + :math.pow(2, -2 * i))
    end)
  end

  @doc """
  Convert an angle in radians to the fixed-point format expected by CORDIC.

  Maps [-π, π) to [-2^(width-1), 2^(width-1))
  """
  def angle_to_fixed(radians, width \\ 16) do
    scale = :math.pow(2, width - 1) / :math.pi()
    round(radians * scale)
  end

  @doc """
  Convert CORDIC fixed-point angle back to radians.
  """
  def fixed_to_angle(fixed, width \\ 16) do
    scale = :math.pi() / :math.pow(2, width - 1)
    fixed * scale
  end
end
