#!/usr/bin/env bash
#
# rebuild-ourfork.sh -- rebuild the nextpnr-xilinx integration branch from the
# topic branches, from scratch, every time.
#
#   scripts/rebuild-ourfork.sh          rebuild + verify
#   scripts/rebuild-ourfork.sh --check  verify only, change nothing
#
# ## Why a script and not a branch you commit to
#
# `ourfork` exists so the radio work can proceed with every fix applied. It is
# NOT where the fixes live. Each fix is one commit on `stable-backports` so it
# stays independently filable upstream, and none of the six has been filed yet.
#
# The failure mode this exists to prevent: someone fixes something on `ourfork`
# directly, the topic branches rot, and by the time anyone tries to send a
# patch upstream the change cannot be extracted from the integration history.
# That already nearly happened -- `fix/cmt-zinv-polarity` was branched off
# `work/tier1` and carried FOURTEEN unrelated commits, so it could not have
# been pushed as a PR. It was rewritten onto the base by cherry-pick, verified
# diff-identical, and the old tip kept as `backup/cmt-on-tier1`.
#
# So: ourfork is derived, disposable and regenerable. If you need a change,
# make it on a topic branch and re-run this.
#
# The guard below enforces that. It refuses to rebuild if `ourfork` contains
# any commit that is not reachable from a topic branch -- i.e. if somebody
# committed here directly -- rather than silently discarding their work.
set -euo pipefail

NXP="${NXP:-$HOME/src/openxc7/nextpnr-xilinx}"
BASE=stable-backports
INTEGRATION=ourfork

# Order matters only for readability of the log; all seven are single-parent
# topic branches off BASE and merge cleanly in any order.
TOPICS=(
  fix/bram-x9-parity-guard
  fix/ilogic-iffdelmux
  fix/cmt-zinv-polarity
  fix/iserdes-ofb-tieoff
  fix/idelay-requires-idelayctrl
  tool/router-arc-diag
  fix/router-reserve-parallel-pips
)

cd "$NXP"
check_only=${1:-}

# --- guard: nothing may live only on ourfork --------------------------------
if git rev-parse --verify -q "$INTEGRATION" >/dev/null; then
  # The generated BRANCHES.md commit is the one thing that legitimately exists
  # only here, so it is excluded by CONTENT (touches nothing but that file)
  # rather than by subject line -- a message is easy to copy by accident, a
  # file list is not.
  orphans=""
  for c in $(git rev-list --no-merges "$INTEGRATION" --not "$BASE" "${TOPICS[@]}"); do
    touched=$(git show --pretty=format: --name-only "$c" | grep -v '^$' | sort -u | tr '\n' ' ')
    [ "$touched" = "BRANCHES.md " ] && continue
    orphans="$orphans$c"$'\n'
  done
  orphans=$(printf '%s' "$orphans")
  if [ -n "$orphans" ]; then
    echo "REFUSING to rebuild: these commits exist only on $INTEGRATION --"
    echo "$orphans" | while read -r c; do echo "  $(git log --oneline -1 "$c")"; done
    echo
    echo "Move them onto a topic branch first. $INTEGRATION is derived, not authored."
    exit 1
  fi
fi

# --- guard: every topic branch must be a clean descendant of BASE -----------
for b in "${TOPICS[@]}"; do
  if ! git merge-base --is-ancestor "$BASE" "$b"; then
    echo "REFUSING: $b is not a descendant of $BASE"; exit 1
  fi
  n=$(git rev-list --count "$BASE..$b")
  if [ "$n" -gt 3 ]; then
    echo "REFUSING: $b carries $n commits -- topic branches stay small and filable"; exit 1
  fi
done

if [ "$check_only" = "--check" ]; then
  echo "all topic branches clean and filable; $INTEGRATION has no orphan commits"
  exit 0
fi

# --- rebuild ----------------------------------------------------------------
prev=$(git rev-parse --verify -q "$INTEGRATION" || true)
git checkout -q -B "$INTEGRATION" "$BASE"

for b in "${TOPICS[@]}"; do
  printf '  merge %-34s ' "$b"
  git merge --no-ff --no-edit "$b" >/dev/null 2>&1 && echo ok || { echo CONFLICT; exit 1; }
done

# --- BRANCHES.md is GENERATED, so it can never drift from reality -----------
{
  echo "# Branch layout"
  echo
  echo "Generated by ehdl/scripts/rebuild-ourfork.sh. Do not edit by hand."
  echo
  echo "\`$BASE\` is upstream openXC7. Every fix is ONE commit on top of it, so"
  echo "each can be sent upstream on its own. \`$INTEGRATION\` is the merge of all"
  echo "of them and is what the radio builds against. It is derived -- never"
  echo "commit to it directly; add a topic branch and re-run the script."
  echo
  printf '| branch | commits | files |\n|---|---|---|\n'
  for b in "${TOPICS[@]}"; do
    printf '| `%s` | %s | %s |\n' "$b" \
      "$(git rev-list --count "$BASE..$b")" \
      "$(git diff --name-only "$BASE..$b" | tr '\n' ' ')"
  done
  echo
  echo "None filed upstream yet."
} > BRANCHES.md

git add BRANCHES.md
git commit -q -m "docs: generated branch layout

Written by ehdl/scripts/rebuild-ourfork.sh. ourfork is rebuilt from the topic
branches on every run, so this file is regenerated rather than maintained."

echo
echo "$INTEGRATION rebuilt: $(git log --oneline -1)"
[ -n "$prev" ] && [ "$prev" != "$(git rev-parse HEAD)" ] && echo "  (was $prev)"

# --- known-answer check: source must match the tree we measured on ----------
if git rev-parse --verify -q backup/cmt-on-tier1 >/dev/null; then
  if [ -z "$(git diff --name-only backup/cmt-on-tier1 "$INTEGRATION" -- common xilinx)" ]; then
    echo "  source identical to backup/cmt-on-tier1 (the tree all measurements were made on)"
  else
    echo "  WARNING: source differs from backup/cmt-on-tier1 -- re-verify on hardware"
    git diff --stat backup/cmt-on-tier1 "$INTEGRATION" -- common xilinx
  fi
fi

echo
echo "Now: cmake --build build -j8 && bash scripts/regress.sh"
echo "And the board. No nextpnr change is finished until the radio decodes at"
echo "deg_per_sample 11.25 / mag_cv 3.4e-4."
